### ISSUE TITLE
Samsung Galaxy Watch5 pro speech problem

### ISSUE THREAD

**Issue by obilginer** [AnujMutha/WearGPT#1]
Dear Anuj,
Thank you for development. I can not get speech output from my watch, could you please investigate the code for solution?
Regards

**Comment by AnujMutha** [comment]
Hey, i apologize for the inconvenience.

I would like to know what default keyboard are you using ? , Also did your watch have "speech service by Google installed", if not please install gboard on your watch and set Google speech engine as default in your TTS setting of your device.

Please revert, if that helps !
Thank you.

**Comment by AnujMutha** [comment]
> Dear Anuj,
> Thank you for development. I can not get speech output from my watch, could you please investigate the code for solution?
> Regards

Hey, i apologize for the inconvenience.

I would like to know what default keyboard are you using ? , Also did your watch have "speech service by Google installed", if not please install gboard on your watch and set Google speech engine as default in your TTS setting of your device.

Please revert, if that helps !
Thank you.
