### ISSUE TITLE
Entered API key successfully ("Valid"), but app doesn't return results

### ISSUE THREAD

**Issue by papermache** [AnujMutha/WearGPT#13]
I am able to input a prompt however the app briefly shows "Thinking. . ." then reverts back to "Response appears here." API key has been accepted by the app.

**Comment by alexandre-viale** [comment]
> I am able to input a prompt however the app briefly shows "Thinking. . ." then reverts back to "Response appears here." API key has been accepted by the app.

I have the same issue on pixel watch, tried over wifi and cellular

**Comment by dayton123** [comment]
> 

>

**Comment by AnujMutha** [comment]
Apologize for your inconveniences,

I would like to inform you guys that there appears to be no issue with the app in terms of its responses. Instead, it seems that the credits provided by OPENAI for your account have been exhausted, leading to the app's inability to respond to your queries.

To clarify this further, I recommend visiting the "View API Usage" (https://platform.openai.com/account/usage) section on the OpenAI website, where you can check the remaining credits count. If the count is zero, it means that you have used up all your free credits or they may have expired. In such cases, you will need to purchase additional credits directly from OpenAI.

It is important to note that certain accounts may not receive free credits from OpenAI, and in those instances, purchasing credits becomes necessary.

Please remember that my app itself is completely free to use at any given time. However, it is OpenAI that charges for the usage of their API.

I hope this information clarifies the situation for you guys.
