### ISSUE TITLE
Won’t take APT Code

### ISSUE THREAD

**Issue by realjustice007** [AnujMutha/WearGPT#4]
Hi.  I’ve never been able to make this app work.  I’ve tried I putting the API key in 15 times and it’s always invalid.  Somethings not right.  Please help.

**Comment by AnujMutha** [comment]
Please make sure you are inserting API Key rightly.
Just make sure you aren't messing up with the letters where you might be considering for ex. letter 'I' (i for ice-cream) as 'l' (capital j for joker)

i would suggest you to use ADB or screen sharing tool such as "SCRCPY" to enter the API Key using your PC.

**Comment by realjustice007** [comment]
Is it possible to enter the API in the phone?   I can only see a way to manually do it on the watch, this is extremely difficult.

**Comment by AnujMutha** [comment]
> Is it possible to enter the API in the phone?   I can only see a way to manually do it on the watch, this is extremely difficult.  

Currently, there's no any companion app for phone
