### ISSUE TITLE
Response speed and couple ideas

### ISSUE THREAD

**Issue by p6002** [AnujMutha/WearGPT#9]
First of all, thanks for the application, very good job.

A couple of things I would like to point out, the speed of response after pressing + or - restarts the application. 
It would be nice to see the ability to enable auto-response by voice. Currently you have to press the speaker button to hear the response.
Additionally, it would be useful to have the voice commands automatically activate when you stop speaking. Currently you have to confirm the processed text and send manually.
Wrist gesture activation would also be useful. I currently run Home Assistant this way on the Galasy Wear 5. 

The ideal way to work, would be if after pressing the microphone button (or whirst gesture), the rest would be done without interacting with the screen.

**Comment by AnujMutha** [comment]
hey @p6002 ,

Thanks for your creative ideas , i would consider them in upcoming updates.
Regarding the +/- issue, please drop a mail at developer.anuj16@gmail.com with thorough explanation, so that i will be able to assist you !
